### ISSUE TITLE
Error when creating new model

### ISSUE THREAD

**Issue by ArseneBrosy** [booskit-codes/PyITAgent#7]
I got this error when using the agent

![image](https://github.com/user-attachments/assets/7f7a6073-934d-4374-8c84-d22a9a542c94)

After a bit of searching i found out that it is because i have a model that start by the name of an another model.
Example:
- MyModel
- MyModelAndMore

so when the agent search the model "MyModel" at model.py, line 34, he find MyModelAndMore and thus try to create MyModel wich result in this error.

I think it could be fixed by changing the line 34 of model.py **from**
endpoint = f'models?limit=1&search={model_name}&sort=name'
**to**
endpoint = f'models?limit=1&search={model_name}&sort=name&order=asc'

Can you try ?

Thanks

**Comment by b00skit** [comment]
https://github.com/booskit-codes/PyITAgent/commit/3a507eb805ea6d3eb36950c108b4e2f1489a9948

Went ahead and merged this with main.
Should reflect in v1.5.1, you can try and redownload the dist and check again.
